name: Build and Push Docker Image

on:
  push:
    branches:
      - dev  # 触发的分支，可以根据你的需求修改
  pull_request:
    branches:
      - dev  # 同样适用于 pull request，针对 main 分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # 获取仓库代码

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # 设置 Docker Buildx

    - name: Log in to Docker Hub
      uses: docker/login-action@v2  # Docker 登录
      with:
        username: shentx  # Docker Hub 用户名
        password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub 密码

    - name: Build Docker image
      run: |
        docker build . --file Dockerfile -t shentx/betterforward:dev  # 构建 Docker 镜像，替换为你的 Docker Hub 用户名和镜像名称
    - name: Push Docker image
      run: |
        docker push shentx/betterforward:dev  # 推送镜像到 Docker Hub，替换为你的 Docker Hub 用户名和镜像名称